### ISSUE TITLE
It is possible to use it strings as keys?

### ISSUE THREAD

**Issue by blajanadrian18** [orchestral/translation#3]
vendor/orchestra/package/resources/lang/ro.json ?

{
    "I love programming.": "Me encanta programar."
}

**Comment by crynobone** [comment]
Never used it with json before.

**Comment by blajanadrian18** [comment]
I added in orchestra/support -> PackageProvider.php -> public function addLanguageComponent this: 

$this->app->make('translator')->addJsonPath($path); 

And it works.

It can also extend support for json? 

Thanks!
